services:
  frontend:
    image: replydev/beatsync-client
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
    build: 
      dockerfile: ./Dockerfile.client
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
        - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws

  backend:
    image: replydev/beatsync-server
    ports:
      - 8080:8080
    build: 
      dockerfile: ./Dockerfile.server